services:
  - type: web
    name: pm25-air-quality-forecasting
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 7860
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
      - key: DATABASE_URL
        sync: false
