[server]
headless = true
port = 8501
fileWatcherType = "none"

[runner]
fastReruns = true

[logger]
level = "error"

[client]
showErrorDetails = false
toolbarMode = "developer"

[browser]
gatherUsageStats = false

